/**
 * Loads toolbar configuration for a component
 */

import ButtonConfig from '../configs/Button.toolbar.json'
import SwitchItemConfig from '../configs/SwitchItem.toolbar.json'
import SwitchGroupConfig from '../configs/SwitchGroup.toolbar.json'
import AvatarConfig from '../configs/Avatar.toolbar.json'
import ToastConfig from '../configs/Toast.toolbar.json'
import BadgeConfig from '../configs/Badge.toolbar.json'
import ChipConfig from '../configs/Chip.toolbar.json'
import LabelConfig from '../configs/Label.toolbar.json'
import BreadcrumbConfig from '../configs/Breadcrumb.toolbar.json'
import AccordionConfig from '../configs/Accordion.toolbar.json'
import AccordionItemConfig from '../configs/AccordionItem.toolbar.json'
import MenuItemConfig from '../configs/MenuItem.toolbar.json'
import MenuConfig from '../configs/Menu.toolbar.json'
import SliderConfig from '../configs/Slider.toolbar.json'
import SegmentedControlConfig from '../configs/SegmentedControl.toolbar.json'
import SegmentedControlItemConfig from '../configs/SegmentedControlItem.toolbar.json'
import AssistiveElementConfig from '../configs/AssistiveElement.toolbar.json'
import TextFieldConfig from '../configs/TextField.toolbar.json'
import TextareaConfig from '../configs/Textarea.toolbar.json'
import CheckboxItemConfig from '../configs/CheckboxItem.toolbar.json'
import CheckboxGroupConfig from '../configs/CheckboxGroup.toolbar.json'
import RadioButtonItemConfig from '../configs/RadioButtonItem.toolbar.json'
import RadioButtonGroupConfig from '../configs/RadioButtonGroup.toolbar.json'
import NumberInputConfig from '../configs/NumberInput.toolbar.json'
import ModalConfig from '../configs/Modal.toolbar.json'
import DropdownConfig from '../configs/Dropdown.toolbar.json'
import AutocompleteConfig from '../configs/Autocomplete.toolbar.json'
import TabsConfig from '../configs/Tabs.toolbar.json'
import TooltipConfig from '../configs/Tooltip.toolbar.json'
import LinkConfig from '../configs/Link.toolbar.json'
import ReadOnlyFieldConfig from '../configs/ReadOnlyField.toolbar.json'
import FileInputConfig from '../configs/FileInput.toolbar.json'
import FileUploadConfig from '../configs/FileUpload.toolbar.json'
import PanelConfig from '../configs/Panel.toolbar.json'
import HoverCardPopoverConfig from '../configs/HoverCardPopover.toolbar.json'
import CardConfig from '../configs/Card.toolbar.json'
import PaginationConfig from '../configs/Pagination.toolbar.json'
import TimePickerConfig from '../configs/TimePicker.toolbar.json'
import DatePickerConfig from '../configs/DatePicker.toolbar.json'
import LoaderConfig from '../configs/Loader.toolbar.json'
import StepperConfig from '../configs/Stepper.toolbar.json'
import TimelineConfig from '../configs/Timeline.toolbar.json'
import TimelineBulletConfig from '../configs/TimelineBullet.toolbar.json'
import TransferListConfig from '../configs/TransferList.toolbar.json'
import TreeConfig from '../configs/Tree.toolbar.json'
import TableConfig from '../configs/Table.toolbar.json'
import TableCellConfig from '../configs/TableCell.toolbar.json'
import TableHeaderConfig from '../configs/TableHeader.toolbar.json'
import TableFooterConfig from '../configs/TableFooter.toolbar.json'
import { buildComponentExtensionGroups } from './componentExtensionToolbar'

export interface ToolbarPropConfig {
  icon: string
  label: string
  visible?: boolean
  group?: Record<string, ToolbarPropConfig> // Props that are grouped under this icon
  propertyType?: 'slider' | 'select' | 'color' | 'text' // Custom property type override
  range?: [number, number] // For slider
  step?: number // For slider
  allowedProps?: string[] // For restricting which properties are visible in a group like text-style
  control?: 'dropdown' | 'segmented' // Control type for options-based props
  options?: Array<string | { label: string; value: string; icon?: string }> // Options for dropdown/segmented controls
  showForVariants?: string[] // Only show this prop when one of these variant values is selected
  /** Target component name for groups generated by the recursica.component extension factory (e.g. "button"). */
  componentRef?: string
}

export interface ToolbarVariantConfig {
  icon: string
  label: string
  optionLabels?: Record<string, string> // Override display labels per option value
}

export interface ToolbarConfig {
  variants?: Record<string, ToolbarVariantConfig>
  props: Record<string, ToolbarPropConfig>
}

/**
 * Merges factory-generated `recursica.component` extension groups into a static
 * ToolbarConfig.  For each extension group:
 *   - If the static config already has a matching prop entry, the factory-generated
 *     children are merged into that entry's `group` (existing hand-authored children
 *     are preserved and take precedence, since they may have richer configs).
 *   - If no static entry exists, the factory-generated entry is added as-is.
 */
function mergeExtensionGroups(config: ToolbarConfig, componentKey: string): ToolbarConfig {
  const extensionGroups = buildComponentExtensionGroups(componentKey)
  if (extensionGroups.length === 0) return config

  const mergedProps = { ...config.props }

  for (const extGroup of extensionGroups) {
    const { propName, groupConfig } = extGroup
    const existing = mergedProps[propName]

    if (existing) {
      // Merge factory children into the existing entry's group.
      // Existing hand-authored children take precedence (don't overwrite them).
      const existingGroup = existing.group ?? {}
      const factoryGroup = groupConfig.group ?? {}
      const mergedGroup: Record<string, ToolbarPropConfig> = { ...factoryGroup, ...existingGroup }
      mergedProps[propName] = { ...existing, group: mergedGroup }
    } else {
      mergedProps[propName] = groupConfig
    }
  }

  return { ...config, props: mergedProps }
}

/**
 * Loads the toolbar config for a component.
 * Extension groups from `recursica.component` tokens are merged in automatically.
 */
export function loadToolbarConfig(componentName: string): ToolbarConfig | null {
  // Convert component name to kebab-case for file name and uikit lookup
  const componentKey = componentName.toLowerCase().replace(/\s+/g, '-')

  let staticConfig: ToolbarConfig | null = null

  switch (componentKey) {
    case 'button':
      staticConfig = ButtonConfig as unknown as ToolbarConfig; break
    case 'switch-item':
    case 'switch group item':
    case 'switch-group-item':
      staticConfig = SwitchItemConfig as unknown as ToolbarConfig; break
    case 'switch-group':
    case 'switch group':
      staticConfig = SwitchGroupConfig as unknown as ToolbarConfig; break
    case 'avatar':
      staticConfig = AvatarConfig as unknown as ToolbarConfig; break
    case 'toast':
      staticConfig = ToastConfig as unknown as ToolbarConfig; break
    case 'badge':
      staticConfig = BadgeConfig as unknown as ToolbarConfig; break
    case 'chip':
      staticConfig = ChipConfig as unknown as ToolbarConfig; break
    case 'label':
      staticConfig = LabelConfig as unknown as ToolbarConfig; break
    case 'breadcrumb':
      staticConfig = BreadcrumbConfig as unknown as ToolbarConfig; break
    case 'accordion':
      staticConfig = AccordionConfig as unknown as ToolbarConfig; break
    case 'accordion-item':
    case 'accordion item':
      staticConfig = AccordionItemConfig as unknown as ToolbarConfig; break
    case 'menu-item':
    case 'menu item':
      staticConfig = MenuItemConfig as unknown as ToolbarConfig; break
    case 'menu':
      staticConfig = MenuConfig as unknown as ToolbarConfig; break
    case 'slider':
      staticConfig = SliderConfig as unknown as ToolbarConfig; break
    case 'segmented-control':
    case 'segmented control':
      staticConfig = SegmentedControlConfig as unknown as ToolbarConfig; break
    case 'segmented-control-item':
    case 'segmented control item':
      staticConfig = SegmentedControlItemConfig as unknown as ToolbarConfig; break
    case 'assistive-element':
    case 'assistive element':
      staticConfig = AssistiveElementConfig as unknown as ToolbarConfig; break
    case 'text-field':
    case 'text field':
      staticConfig = TextFieldConfig as unknown as ToolbarConfig; break
    case 'textarea':
      staticConfig = TextareaConfig as unknown as ToolbarConfig; break
    case 'checkbox-item':
    case 'checkbox item':
    case 'checkbox-group-item':
      staticConfig = CheckboxItemConfig as unknown as ToolbarConfig; break
    case 'checkbox-group':
    case 'checkbox group':
      staticConfig = CheckboxGroupConfig as unknown as ToolbarConfig; break
    case 'radio-button-item':
    case 'radio button item':
    case 'radio-button-group-item':
      staticConfig = RadioButtonItemConfig as unknown as ToolbarConfig; break
    case 'radio-button-group':
    case 'radio button group':
      staticConfig = RadioButtonGroupConfig as unknown as ToolbarConfig; break
    case 'number-input':
    case 'number input':
    case 'numberinput':
      staticConfig = NumberInputConfig as unknown as ToolbarConfig; break
    case 'modal':
      staticConfig = ModalConfig as unknown as ToolbarConfig; break
    case 'dropdown':
      staticConfig = DropdownConfig as unknown as ToolbarConfig; break
    case 'autocomplete':
      staticConfig = AutocompleteConfig as unknown as ToolbarConfig; break
    case 'tabs':
      staticConfig = TabsConfig as unknown as ToolbarConfig; break
    case 'tooltip':
      staticConfig = TooltipConfig as unknown as ToolbarConfig; break
    case 'link':
      staticConfig = LinkConfig as unknown as ToolbarConfig; break
    case 'read-only-field':
    case 'read only field':
    case 'readonlyfield':
      staticConfig = ReadOnlyFieldConfig as unknown as ToolbarConfig; break
    case 'file-input':
    case 'file input':
      staticConfig = FileInputConfig as unknown as ToolbarConfig; break
    case 'file-upload':
    case 'file upload':
      staticConfig = FileUploadConfig as unknown as ToolbarConfig; break
    case 'panel':
      staticConfig = PanelConfig as unknown as ToolbarConfig; break
    case 'pagination':
      staticConfig = PaginationConfig as unknown as ToolbarConfig; break
    case 'hover-card-/-popover':
    case 'hover-card-popover':
    case 'hover card / popover':
    case 'hovercard':
    case 'hovercardpopover':
      staticConfig = HoverCardPopoverConfig as unknown as ToolbarConfig; break
    case 'card':
      staticConfig = CardConfig as unknown as ToolbarConfig; break
    case 'time-picker':
    case 'time picker':
    case 'timepicker':
      staticConfig = TimePickerConfig as unknown as ToolbarConfig; break
    case 'date-picker':
    case 'date picker':
    case 'datepicker':
      staticConfig = DatePickerConfig as unknown as ToolbarConfig; break
    case 'loader':
      staticConfig = LoaderConfig as unknown as ToolbarConfig; break
    case 'stepper':
      staticConfig = StepperConfig as unknown as ToolbarConfig; break
    case 'timeline':
      staticConfig = TimelineConfig as unknown as ToolbarConfig; break
    case 'timeline-bullet':
    case 'timeline bullet':
      staticConfig = TimelineBulletConfig as unknown as ToolbarConfig; break
    case 'transfer-list':
    case 'transfer list':
    case 'transferlist':
      staticConfig = TransferListConfig as unknown as ToolbarConfig; break
    case 'tree':
      staticConfig = TreeConfig as unknown as ToolbarConfig; break
    case 'table':
      staticConfig = TableConfig as unknown as ToolbarConfig; break
    case 'table-cell':
    case 'table cell':
      staticConfig = TableCellConfig as unknown as ToolbarConfig; break
    case 'table-header':
    case 'table header':
      staticConfig = TableHeaderConfig as unknown as ToolbarConfig; break
    case 'table-footer':
    case 'table footer':
      staticConfig = TableFooterConfig as unknown as ToolbarConfig; break
    default:
      staticConfig = null
  }

  if (!staticConfig) {
    // Even without a static config, if the component has extension groups,
    // synthesise a minimal config from the factory alone.
    const extensionGroups = buildComponentExtensionGroups(componentKey)
    if (extensionGroups.length === 0) return null
    const syntheticProps: Record<string, ToolbarPropConfig> = {}
    for (const g of extensionGroups) syntheticProps[g.propName] = g.groupConfig
    return { props: syntheticProps }
  }

  return mergeExtensionGroups(staticConfig, componentKey)
}

/**
 * Gets the config for a specific prop, including searching inside groups
 */
export function getPropConfig(
  componentName: string,
  propName: string
): ToolbarPropConfig | null {
  const config = loadToolbarConfig(componentName)
  if (!config) return null

  const propKey = propName.toLowerCase()

  // First check at the root level
  if (config.props[propKey]) {
    return config.props[propKey]
  }

  // Then check inside groups
  for (const parentPropConfig of Object.values(config.props)) {
    if (parentPropConfig.group && parentPropConfig.group[propKey]) {
      return parentPropConfig.group[propKey]
    }
  }

  return null
}

/**
 * Gets the icon name for a prop
 */
export function getPropIcon(componentName: string, propName: string): string | null {
  const config = getPropConfig(componentName, propName)
  return config?.icon || null
}

/**
 * Gets the label for a prop
 */
export function getPropLabel(componentName: string, propName: string): string | null {
  const config = getPropConfig(componentName, propName)
  return config?.label || null
}

/**
 * Gets the visible property for a prop (defaults to true if not specified)
 */
export function getPropVisible(componentName: string, propName: string): boolean {
  const config = getPropConfig(componentName, propName)
  return config?.visible !== false // Default to true if not specified
}

/**
 * Checks if a prop is grouped under another prop
 */
export function getGroupedPropParent(
  componentName: string,
  propName: string
): string | null {
  const config = loadToolbarConfig(componentName)
  if (!config) return null

  const propKey = propName.toLowerCase()

  // Check if any prop has this prop in its group
  for (const [key, propConfig] of Object.entries(config.props)) {
    if (propConfig.group && propConfig.group[propKey]) {
      return key
    }
  }

  return null
}

/**
 * Gets the config for a grouped prop
 */
export function getGroupedPropConfig(
  componentName: string,
  parentPropName: string,
  groupedPropName: string
): ToolbarPropConfig | null {
  const config = getPropConfig(componentName, parentPropName)
  if (!config || !config.group) return null

  const groupedPropKey = groupedPropName.toLowerCase()
  return config.group[groupedPropKey] || null
}

/**
 * Gets all grouped props for a parent prop
 */
export function getGroupedProps(
  componentName: string,
  parentPropName: string
): Record<string, ToolbarPropConfig> | null {
  const config = getPropConfig(componentName, parentPropName)
  return config?.group || null
}

/**
 * Gets the config for a variant prop (e.g., "color", "size", "style")
 */
export function getVariantConfig(
  componentName: string,
  variantPropName: string
): ToolbarVariantConfig | null {
  const config = loadToolbarConfig(componentName)
  if (!config || !config.variants) return null

  const variantKey = variantPropName.toLowerCase()
  return config.variants[variantKey] || null
}

/**
 * Gets the icon name for a variant prop
 */
export function getVariantIcon(componentName: string, variantPropName: string): string | null {
  const config = getVariantConfig(componentName, variantPropName)
  return config?.icon || null
}

/**
 * Gets the label for a variant prop
 */
export function getVariantLabel(componentName: string, variantPropName: string): string | null {
  const config = getVariantConfig(componentName, variantPropName)
  return config?.label || null
}

/**
 * Gets the display label for a specific option value within a variant axis.
 * Falls back to null if no override is defined (caller should use toSentenceCase).
 */
export function getVariantOptionLabel(
  componentName: string,
  variantPropName: string,
  optionValue: string
): string | null {
  const config = getVariantConfig(componentName, variantPropName)
  return config?.optionLabels?.[optionValue] ?? null
}

