/**
 * Runtime Scoped CSS Engine
 *
 * Generates a <style> element that creates generic-name CSS variable aliases
 * inside theme/layer selectors, pointing at specific-name vars on :root.
 *
 * This lets forge dogfood its own scoped CSS export:
 * - :root holds all vars with specific (full-path) names
 * - Theme selectors set generic (short) aliases → var(specificNameOnRoot)
 * - Consumer code reads generic names; cascade resolves the theme/layer
 */

import type { CssVarMap } from './apply'

const STYLE_ID = 'recursica-scoped'
const PREFIX = '--recursica_'

/** Scoped alias: a generic var name that aliases a specific var name. */
interface ScopedAlias {
  genericName: string
  specificName: string
}

/**
 * Classifies a specific CSS var name and returns the generic alias info,
 * or null if no scoping applies (tokens, brand.typography, etc. stay on :root only).
 *
 * Mappings (using underscore-delimited format):
 * - brand_themes_{theme}_palettes_... → brand_palettes_...  (theme scope)
 * - brand_themes_{theme}_layers_layer-{N}_... → brand_layer_{N}_...  (theme+layer scope)
 * - brand_themes_{theme}_states_... → brand_states_...  (theme scope)
 * - brand_themes_{theme}_text-emphasis_... → brand_text-emphasis_...  (theme scope)
 * - brand_themes_{theme}_elevations_... → brand_elevations_...  (theme scope)
 * - ui-kit_themes_{theme}_layer_{N}_... → ui-kit_...  (theme+layer scope, canonical name)
 */
function classifyVar(specificName: string): {
  theme: 'light' | 'dark'
  layer?: string
  genericName: string
} | null {
  // Brand theme-scoped vars: --recursica_brand_themes_{theme}_{rest}
  const brandThemeMatch = specificName.match(
    /^--recursica_brand_themes_(light|dark)_(.+)$/
  )
  if (brandThemeMatch) {
    const theme = brandThemeMatch[1] as 'light' | 'dark'
    const rest = brandThemeMatch[2]

    // Check if it's a layer var: layers_layer-{N}_{rest}
    const layerMatch = rest.match(/^layers_layer-(\d+)_(.+)$/)
    if (layerMatch) {
      const layerNum = layerMatch[1]
      const layerRest = layerMatch[2]
      return {
        theme,
        layer: layerNum,
        genericName: `${PREFIX}brand_layer_${layerNum}_${layerRest}`,
      }
    }

    // Theme-only brand var (palettes, states, text-emphasis, elevations, etc.)
    return {
      theme,
      genericName: `${PREFIX}brand_${rest}`,
    }
  }

  // UI-kit layer-specific: --recursica_ui-kit_themes_{theme}_layer_{N}_{rest}
  const uikitLayerMatch = specificName.match(
    /^--recursica_ui-kit_themes_(light|dark)_layer_(\d+)_(.+)$/
  )
  if (uikitLayerMatch) {
    const theme = uikitLayerMatch[1] as 'light' | 'dark'
    const layerNum = uikitLayerMatch[2]
    const rest = uikitLayerMatch[3]
    return {
      theme,
      layer: layerNum,
      genericName: `${PREFIX}ui-kit_${rest}`,
    }
  }

  // UI-kit theme-scoped (components, globals, etc.): --recursica_ui-kit_themes_{theme}_{rest}
  const uikitThemeMatch = specificName.match(
    /^--recursica_ui-kit_themes_(light|dark)_(.+)$/
  )
  if (uikitThemeMatch) {
    const theme = uikitThemeMatch[1] as 'light' | 'dark'
    const rest = uikitThemeMatch[2]
    return {
      theme,
      genericName: `${PREFIX}ui-kit_${rest}`,
    }
  }

  // Not scoped (tokens, brand.typography, brand.dimensions)
  return null
}

/**
 * Generates the CSS text for scoped alias blocks.
 */
function generateScopedCss(allSpecificVars: CssVarMap): string {
  // Collect aliases by scope
  const themeOnly: Map<string, ScopedAlias[]> = new Map()
  const themePlusLayer: Map<string, ScopedAlias[]> = new Map()

  for (const specificName of Object.keys(allSpecificVars)) {
    const info = classifyVar(specificName)
    if (!info) continue

    const alias: ScopedAlias = {
      genericName: info.genericName,
      specificName,
    }

    if (info.layer != null) {
      const key = `${info.theme}+${info.layer}`
      if (!themePlusLayer.has(key)) themePlusLayer.set(key, [])
      themePlusLayer.get(key)!.push(alias)
    } else {
      if (!themeOnly.has(info.theme)) themeOnly.set(info.theme, [])
      themeOnly.get(info.theme)!.push(alias)
    }
  }

  let css = '/* Generated by scopedCssEngine — do not edit */\n\n'

  // Theme-only blocks
  for (const theme of ['light', 'dark'] as const) {
    const aliases = themeOnly.get(theme)
    if (!aliases || aliases.length === 0) continue
    css += `[data-recursica-theme="${theme}"] {\n`
    for (const { genericName, specificName } of aliases) {
      css += `  ${genericName}: var(${specificName});\n`
    }
    css += '}\n\n'
  }

  // Theme + layer blocks
  for (const theme of ['light', 'dark'] as const) {
    for (const layer of ['0', '1', '2', '3']) {
      const key = `${theme}+${layer}`
      const aliases = themePlusLayer.get(key)
      if (!aliases || aliases.length === 0) continue
      css += `[data-recursica-theme="${theme}"][data-recursica-layer="${layer}"],\n`
      css += `[data-recursica-theme="${theme}"] [data-recursica-layer="${layer}"] {\n`
      for (const { genericName, specificName } of aliases) {
        css += `  ${genericName}: var(${specificName});\n`
      }
      css += '}\n\n'
    }
  }

  return css
}

/**
 * Updates the runtime scoped CSS <style> element.
 * Call this after applyCssVars() with the full var map.
 */
export function updateScopedCss(allSpecificVars: CssVarMap): void {
  const css = generateScopedCss(allSpecificVars)

  let styleEl = document.getElementById(STYLE_ID) as HTMLStyleElement | null
  if (!styleEl) {
    styleEl = document.createElement('style')
    styleEl.id = STYLE_ID
    document.head.appendChild(styleEl)
  }
  styleEl.textContent = css
}

/**
 * Sets the current theme on the document root element.
 */
export function setThemeAttribute(theme: 'light' | 'dark'): void {
  document.documentElement.setAttribute('data-recursica-theme', theme)
}

/**
 * Sets the layer attribute on a given element.
 */
export function setLayerAttribute(element: HTMLElement, layer: string): void {
  element.setAttribute('data-recursica-layer', layer)
}

/**
 * Gets the current theme from the document root, defaulting to 'light'.
 */
export function getThemeAttribute(): 'light' | 'dark' {
  const val = document.documentElement.getAttribute('data-recursica-theme')
  return val === 'dark' ? 'dark' : 'light'
}
